/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.z.lament.obrc;


public class App {
    public String getGreeting() {
        return "Hello, this is my 1brc demo";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    }
}
